-- MySQL Script generated by MySQL Workbench
-- Mon Nov  3 02:32:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cinema_last
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cinema_last
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinema_last` DEFAULT CHARACTER SET utf8 ;
USE `Cinema_last` ;

-- -----------------------------------------------------
-- Table `Cinema_last`.`CINEMAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_last`.`CINEMAS` ;

CREATE TABLE IF NOT EXISTS `Cinema_last`.`CINEMAS` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `SEATS` VARCHAR(45) NOT NULL,
  `3D` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema_last`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_last`.`user` ;

CREATE TABLE IF NOT EXISTS `Cinema_last`.`user` (
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema_last`.`CONTENT_ADMIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_last`.`CONTENT_ADMIN` ;

CREATE TABLE IF NOT EXISTS `Cinema_last`.`CONTENT_ADMIN` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `user_username` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`, `user_username`),
  INDEX `fk_CONTENT_ADMIN_user1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_CONTENT_ADMIN_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `Cinema_last`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema_last`.`MOVIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_last`.`MOVIES` ;

CREATE TABLE IF NOT EXISTS `Cinema_last`.`MOVIES` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `CONTENT` VARCHAR(45) NOT NULL,
  `LENGTH` INT NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `SUMMARY` VARCHAR(45) NOT NULL,
  `CONTENT_ADMIN_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `NAME`, `CONTENT_ADMIN_ID`),
  INDEX `fk_MOVIES_CONTENT_ADMIN1_idx` (`CONTENT_ADMIN_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MOVIES_CONTENT_ADMIN1`
    FOREIGN KEY (`CONTENT_ADMIN_ID`)
    REFERENCES `Cinema_last`.`CONTENT_ADMIN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema_last`.`PROVOLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_last`.`PROVOLES` ;

CREATE TABLE IF NOT EXISTS `Cinema_last`.`PROVOLES` (
  `Screening_Id` INT NOT NULL,
  `MOVIES_ID` INT NOT NULL,
  `MOVIES_NAME` VARCHAR(45) NOT NULL,
  `CINEMAS_ID` INT NOT NULL,
  `CONTENT_ADMIN_ID` INT NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Seats_Available` INT NOT NULL,
  `Hour` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Screening_Id`, `MOVIES_ID`, `MOVIES_NAME`, `CINEMAS_ID`, `CONTENT_ADMIN_ID`),
  INDEX `fk_MOVIES_has_CINEMAS_CINEMAS1_idx` (`CINEMAS_ID` ASC) VISIBLE,
  INDEX `fk_MOVIES_has_CINEMAS_MOVIES_idx` (`MOVIES_ID` ASC, `MOVIES_NAME` ASC) VISIBLE,
  INDEX `fk_PROVOLES_CONTENT_ADMIN1_idx` (`CONTENT_ADMIN_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MOVIES_has_CINEMAS_MOVIES`
    FOREIGN KEY (`MOVIES_ID` , `MOVIES_NAME`)
    REFERENCES `Cinema_last`.`MOVIES` (`ID` , `NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVIES_has_CINEMAS_CINEMAS1`
    FOREIGN KEY (`CINEMAS_ID`)
    REFERENCES `Cinema_last`.`CINEMAS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROVOLES_CONTENT_ADMIN1`
    FOREIGN KEY (`CONTENT_ADMIN_ID`)
    REFERENCES `Cinema_last`.`CONTENT_ADMIN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema_last`.`CUSTOMERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_last`.`CUSTOMERS` ;

CREATE TABLE IF NOT EXISTS `Cinema_last`.`CUSTOMERS` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `user_username` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`, `user_username`),
  INDEX `fk_CUSTOMERS_user1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_CUSTOMERS_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `Cinema_last`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema_last`.`RESERVATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_last`.`RESERVATIONS` ;

CREATE TABLE IF NOT EXISTS `Cinema_last`.`RESERVATIONS` (
  `PROVOLES_Screening_Id` INT NOT NULL,
  `CUSTOMERS_ID` INT NOT NULL,
  `SEATS_Booked` INT NOT NULL,
  PRIMARY KEY (`PROVOLES_Screening_Id`, `CUSTOMERS_ID`),
  INDEX `fk_PROVOLES_has_CUSTOMERS_CUSTOMERS1_idx` (`CUSTOMERS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROVOLES_has_CUSTOMERS_PROVOLES1`
    FOREIGN KEY (`PROVOLES_Screening_Id`)
    REFERENCES `Cinema_last`.`PROVOLES` (`Screening_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROVOLES_has_CUSTOMERS_CUSTOMERS1`
    FOREIGN KEY (`CUSTOMERS_ID`)
    REFERENCES `Cinema_last`.`CUSTOMERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema_last`.`ADMINS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cinema_last`.`ADMINS` ;

CREATE TABLE IF NOT EXISTS `Cinema_last`.`ADMINS` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `user_username` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`, `user_username`),
  INDEX `fk_ADMINS_user1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_ADMINS_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `Cinema_last`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
